runtime: java17
entrypoint: java -Xmx64m -jar todo-0.0.1-SNAPSHOT.jar
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1