runtime: java17
entrypoint: java -Xmx64m -jar todo-0.0.1-SNAPSHOT.jar
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
  SPRING_DATASOURCE_URL: jdbc:mysql:///todo
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: user
  GOOGLE_CLOUD_PROJECT: todo-app-437107
  INSTANCE_CONNECTION_NAME:  todo-app-437107:asia-southeast2:todo
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
